"$schema" = 'https://starship.rs/config-schema.json'

add_newline = true
command_timeout = 5000

palette = "techbase"

[directory]
style = "bright_white"
truncation_length = 5
read_only = " 󰌾"

[character]
success_symbol = "[❯](bright_blue)"
error_symbol = "[❯](red)"

[git_branch]
format = "[$symbol$branch ]($style)"
style = "bright_black"
symbol = " "

[git_status]
disabled = true

[lua]
disabled = false
format = '[$symbol($version )]($style)'
symbol = " "

[python]
disabled = false
format = '[${symbol}(${version} )$virtualenv]($style)'
style = "yellow"
symbol = "  "
detect_extensions = []

[rust]
disabled = false
format = '[$symbol($version )]($style)'
symbol = "󱘗 "

[cmd_duration]
disabled = false
format = " [$duration]($style) "
style = "bright_purple"

[package]
disabled = true

[palettes.techbase]
bg = "#080808"
fg = "#D6DDEA"
black = "#191d23"
red = "#942B27"
green = "#366A4C"
yellow = "#E9B872"
blue = "#3F58BB"
purple = "#BCB6EC"
cyan = "#1A8C9B"
white = "#CCD5E5"
bright_black = "#474B65"
bright_red = "#ff5454"
bright_green = "#0EC256"
bright_yellow = "#FFA630"
bright_blue = "#6A8BE3"
bright_purple = "#FFC0C5"
bright_cyan = "#74BAA8"
bright_white = "#B7C4FF"
