background = 0xFF080808
base = 0xFF080808
alternate_base = 0xFF2C2C2C
text = 0xFFB2B2B2
bright_text = 0xFFE4E4E4
accent = 0xFFEEEEEE
accent_secondary = 0xFFD683E8

font_family = Iosevka Nerd Font
font_family_monospace = ZedMono Nerd Font

icon_theme = MoreWaita
