# Essentials
set -g default-terminal "tmux-256color"
set -gq allow-passthrough on

set -ag terminal-features ",*:RGB"
set -as terminal-features 'xterm*:extkeys'
set -as terminal-overrides ',*:Smulx=\E[4::%p1%dm'
set -as terminal-overrides ',*:Setulc=\E[58::2::%p1%{65536}%/%d::%p1%{256}%/%{255}%&%d::%p1%{255}%&%d%;m'

set -g default-command "${SHELL}"
set -g xterm-keys on
set -s extended-keys on

# General
set -g mouse on
set -sg escape-time 0
set -g base-index 1
set -g pane-base-index 1
set -g focus-events on

set -g status-position top
set -g aggressive-resize on

unbind-key C-b
set -g prefix C-q
set -g detach-on-destroy off

# Keybinds
# utilities
unbind r
bind r source-file ~/.config/tmux/tmux.conf \; display-message "Configuration reloaded!"
unbind %
bind | split-window -h -c "#{pane_current_path}"
unbind '"'
bind - split-window -v -c "#{pane_current_path}"
unbind v
bind v copy-mode

# resize pane
bind -r j resize-pane -D 5
bind -r k resize-pane -U 5
bind -r h resize-pane -L 5
bind -r l resize-pane -R 5

# maximize
bind -r m resize-pane -Z

# exit pane
bind x kill-pane

# vim movement navigations and selection
set-window-option -g mode-keys vi
bind -T copy-mode-vi 'v' send -X begin-selection
bind -T copy-mode-vi 'y' send -X copy-selection
unbind -T copy-mode-vi MouseDragEnd1Pane

# UI
## status line, windows, pane and message colors.
set -g message-style "bg=#1c1c1c,fg=#9c9c9c"
set -g pane-active-border-style "bg=#080808,fg=#80a0ff"
set -g pane-border-style "bg=#080808,fg=#303030"
set -g status-style "bg=#1c1c1c,fg=#9c9c9c"
setw -g window-status-activity-style none
setw -g window-status-current-style "bg=default,fg=#80a0ff,bold"
## active and inactive window style.
setw -g window-status-current-format "  #I #[fg=#c6c6c6,bold] #[fg=default]#W#[fg=#e65e72]#{?window_flags,#{window_flags}, }#[fg=default] "
setw -g window-status-format "  #I  #W#[fg=#e65e72]#{?window_flags,#{window_flags}, }#[fg=default] "
## status bar components and style.
set -g status-left "#{?client_prefix,#[fg=#e65e72],#[fg=#8cc85f]}\uebc8  #{?client_prefix,#[fg=#e65e72],#[fg=#c6c6c6]}#[bold]#S #{?client_prefix,#[fg=#e65e72],#[fg=#f09479]}\uf101 "
set -g status-right "#[fg=#f09479] #[fg=#e65e72]#(cd #{pane_current_path} && git rev-parse --abbrev-ref HEAD 2>/dev/null) "

# TMUX Plugin Manager
set-environment -g TMUX_PLUGIN_MANAGER_PATH ~/.config/tmux/plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'christoomey/vim-tmux-navigator'

# tmux-continuum needs to be placed last for autosave to be working
set -g @plugin 'omerxx/tmux-sessionx'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'

# plugins configuration
set -g @sessionx-bind 'o'
set -g @resurrect-capture-pane-content 'on'
set -g @continuum-restore 'on'

# Initialize TMUX Plugin Manager
run '~/.config/tmux/plugins/tpm/tpm'
